import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        tertiary: "#6d5e00",
        outline: "#737784",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#171c20",
        "surface-bright": "#faf9fa",
        primary: "#094cb2",
        "on-tertiary-container": "#4a3f00",
        "on-secondary-fixed-variant": "#42474b",
        "on-secondary-container": "#606569",
        "inverse-primary": "#b1c5ff",
        "on-surface": "#1b1c1d",
        "secondary-fixed": "#dfe3e8",
        "on-primary-fixed-variant": "#00419d",
        "tertiary-fixed-dim": "#dcc661",
        "on-primary-fixed": "#001946",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b1c5ff",
        "tertiary-container": "#bfab49",
        "surface-container": "#efedee",
        "on-primary-container": "#e7ebff",
        "secondary-fixed-dim": "#c2c7cc",
        "on-error-container": "#93000a",
        "surface-dim": "#dbdadb",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#434653",
        "surface-variant": "#e3e2e3",
        "surface-container-high": "#e9e8e9",
        surface: "#faf9fa",
        "on-tertiary-fixed": "#211b00",
        "error-container": "#ffdad6",
        "on-background": "#1b1c1d",
        "on-tertiary-fixed-variant": "#524600",
        "inverse-surface": "#303031",
        error: "#ba1a1a",
        "primary-fixed": "#d9e2ff",
        "surface-container-low": "#f5f3f4",
        "secondary-container": "#dfe3e8",
        secondary: "#5a5f63",
        "tertiary-fixed": "#f9e37a",
        "outline-variant": "#c3c6d5",
        background: "#faf9fa",
        "primary-container": "#3366cc",
        "inverse-on-surface": "#f2f0f1",
        "surface-tint": "#2259bf",
        "on-error": "#ffffff",
        "surface-container-highest": "#e3e2e3",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        md: "16px",
        xs: "4px",
        "sidebar-collapsed": "64px",
        lg: "24px",
        xl: "32px",
        unit: "4px",
        "sidebar-width": "240px",
        gutter: "1px",
        sm: "8px",
      },
      fontFamily: {
        "label-caps": ["Inter"],
        "body-sm": ["Inter"],
        "title-sm": ["Inter"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "code-sm": ["JetBrains Mono"],
        "body-md": ["Inter"],
        headline: ["Noto Serif"],
        display: ["Noto Serif"],
        body: ["Inter"],
        label: ["Public Sans"],
      },
      fontSize: {
        "label-caps": [
          "11px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "display-lg": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-md": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};

export default config;
